name: investmentresearch
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.9.3
  - bs4=4.9.3
  - jupyter=1.0.0
  - pandas=1.1.3
  - pip=20.2.4
  - pylint=2.6.0
  - python=3.8.5

